### ISSUE TITLE
Lightbox can't be open on textlink of attachments when protected is on

### ISSUE THREAD

**Issue by mahagr** [Kunena/Kunena-Forum#2802]
Pulls #2774 and #2790 doesn't really work as it doesn't fix lightbox issues.

1) Think of photography forum with a lot of thumbnail images in it. All the 3MB files will be loaded instead of smaller thumbs.
2) It also doesn't work with protected messages if SEF is turned off.

We need to fix lightbox script instead and remove file type check from it.

**Comment by mahagr** [comment]
I suggest putting the parameter (true) back and fixing javascript to support arbitrary urls and not requiring files to end on .jpg etc..

**Comment by xillibit** [comment]
I have tried by reverting my changes the link put in thumbnail is ```http://127.0.0.1/joomla3.4.0/forum/attachment/1/thumb/blech.png``` there isn't urls like that put ```http://127.0.0.1/joomla3.4.0/index.php?option=com_kunena&view=attachment&id=1&thumb=1&format=raw```

Lightbox can be opened with sef on and sef off if i don't load thumbnail version

**Comment by xillibit** [comment]
It seems that thumbnails aren't generated on k3.1 and k3.0.7, if i upload an image of 590 pixels x 250 pixels it displayed in message at this resolution but it is resized CSS to fit in the message

**Comment by 810** [comment]
is fixed and merged

**Comment by xillibit** [comment]
It's not fixed totally because there aren't thumbnails displayed but images in full size

**Comment by rich20** [comment]
Lightbox can't open text links of images, unless it's uploaded another image in the same message (via upload). Regardless of whether protect is on or off.

**Comment by rich20** [comment]
- [x] Success
