### ISSUE TITLE
Crypsis: When CB plugin is enabled, text overlaps Avatars on Index

### ISSUE THREAD

**Issue by GJSchaller** [Kunena/Kunena-Forum#2965]
When the CD plugin for Kunena is enabled, the text on the index page overlaps the CB-generated Avatars, as seen below:

![capture](https://cloud.githubusercontent.com/assets/2761607/7136522/bee2e224-e27f-11e4-80f6-550cbe16b7ef.PNG)

**Comment by 810** [comment]
fixed and merged

**Comment by GJSchaller** [comment]
Still seeing this behavior:

http://template.knightrealms.com/forum/index.html
