### ISSUE TITLE
[K4.0] Crypsis : When you choose own icon folder for a category, all categories use these icons

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#3251]
http://www.kunena.org/forum/kunena-4-0-issues-and-bug-reports/133964-topic-icon-folder-changes-in-k-4-0

**Comment by rich20** [comment]
Is a bit more complicated. The icons will displayed from the category where a topic was last created.

**Comment by sozzled** [comment]
We also need to ensure that the behaviour is consistent for both the Crypsis and Blue Eagle templates.

**Comment by rich20** [comment]
> Is a bit more complicated. The icons will displayed from the category where a topic was last created.

It's still the same.

**Comment by 810** [comment]
@rich20 I think this has been fixed. can you recheck

**Comment by rich20** [comment]
This bug still exists.

**Comment by 810** [comment]
I just merged the fix, could you check it again

**Comment by rich20** [comment]
This bug still exists.
Example: If you create for the category "Welcome Mat" own images it works only if you write in this category. But the images switch in all categories.
If you write in the category "Suggestion Box" goes all back to the default images. Also in the category "Welcome Mat".
Summary:
It shows always the images from the category, where the last post was written.

**Comment by 810** [comment]
could you check it again

---

Still the issue

**Comment by 810** [comment]
we need to add a new column after icon_id on *kunena_topics:
icon_name

Then we can improve the getTopicIcon
$icon = $topic->icon_name; 

Also on new/edit topic/moderate, the icon name must be saved on the new column

For now its all hard coded.

@xillibit could you do this for K5.0

**Comment by xillibit** [comment]
I will take a look for k5.0

**Comment by 810** [comment]
fixed and merged already
