### ISSUE TITLE
Moved topics are untraceable if shadow topic pointing to new location

### ISSUE THREAD

**Issue by rich20** [Kunena/Kunena-Forum#6386]
If you use the option "Leave shadow topic pointing to new location" you get an internal error and 404 Not Found
Kunena Internal Error: Please contact the site administrator to fix this issue! (debug shows not more) 
You can still see the topic in Recent Topics or in the category but if you click on it you get 404 Not Found

**Comment by rich20** [comment]
Addition: it shows this error:

<strike>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '->id} ORDER BY time ASC, id ASC' at line 1</strike>

**Comment by xillibit** [comment]
> 
> 
> Addition: it shows this error:
> 
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '->id} ORDER BY time ASC, id ASC' at line 1

It has been fixed here : https://github.com/Kunena/Kunena-Forum/commit/8c40c16952cc520ad3be87de7d23ebb1bf838569

**Comment by rich20** [comment]
Yes, move topics works now, but the error with the shadow topic is not fixed. And the error message is back because I have installed the version with your last commit https://github.com/Kunena/Kunena-Forum/pull/6388/commits.
Is this commit not up to date?

**Comment by xillibit** [comment]
Yes, the branch in PR 6388 wasn't updated

**Comment by rich20** [comment]
<strike>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '->id} ORDER BY time ASC, id ASC' at line 1</strike>
Ok, then ignore this error message please.

**Comment by rich20** [comment]
This error does not exist anymore.
